import type { CatalogItem } from "../types/catalog.ts";

/**
 * Planter modules. `quantityPerSide` lets pricing scale planters with the
 * pavilion footprint instead of hard-coding a count in the UI.
 */
export const PLANTERS: CatalogItem[] = [
  {
    id: "PLANTER-BOX-001",
    sku: "PLT-BOX-01",
    category: "planter",
    name: "Edge Planter Box",
    status: "active",
    description:
      "Long timber-faced boxes that run along the pavilion edge under the bench line.",
    price: { amount: 640, currency: "SAR", status: "placeholder" },
    pricingMode: "perUnit",
    assetKey: "planter:edge",
    meta: { unitsPerPavilion: 4, heightMm: 420, depthMm: 350 },
  },
  {
    id: "PLANTER-CORNER-001",
    sku: "PLT-COR-01",
    category: "planter",
    name: "Corner Planter",
    status: "active",
    description: "Taller planters at the posts, good for structural greenery.",
    price: { amount: 480, currency: "SAR", status: "placeholder" },
    pricingMode: "perUnit",
    assetKey: "planter:corner",
    meta: { unitsPerPavilion: 4, heightMm: 620, depthMm: 380 },
  },
  {
    id: "PLANTER-HANG-001",
    sku: "PLT-HNG-01",
    category: "planter",
    name: "Hanging Planter Set",
    status: "active",
    description: "Suspended pots hung from the roof frame.",
    price: { amount: 390, currency: "SAR", status: "placeholder" },
    pricingMode: "perUnit",
    assetKey: "planter:hanging",
    meta: { unitsPerPavilion: 4, heightMm: 260 },
  },
  {
    id: "PLANTER-TRELLIS-001",
    sku: "PLT-TRL-01",
    category: "planter",
    name: "Trellis Post Module",
    status: "active",
    description:
      "A vertical trellis fixed to the posts. Required support for climbing plants.",
    price: { amount: 520, currency: "SAR", status: "placeholder" },
    pricingMode: "perUnit",
    assetKey: "trellis:post",
    meta: { unitsPerPavilion: 4, heightMm: 2100, isSupport: true },
  },
  {
    id: "PLANTER-AQUA-001",
    sku: "PLT-AQU-01",
    category: "planter",
    name: "Aquatic Planting Tray",
    status: "active",
    description: "In-tank planting trays for the aquarium.",
    price: { amount: 260, currency: "SAR", status: "placeholder" },
    pricingMode: "perUnit",
    requires: ["AQUARIUM"],
    assetKey: "planter:aquatic",
    meta: { unitsPerPavilion: 2 },
  },
];

/**
 * Demo plant catalog. `support` declares a dependency the rules engine
 * turns into a warning or an auto-required item.
 */
export const PLANTS: CatalogItem[] = [
  {
    id: "PLANT-CLIMB-001",
    sku: "PLN-CLB-01",
    category: "plant",
    name: "Climbing Jasmine",
    status: "active",
    description:
      "Scented climber trained up the posts. Needs a trellis or comparable support.",
    price: { amount: 210, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    requires: ["PLANTER-TRELLIS-001"],
    tags: ["climbing", "scented"],
    assetKey: "plant:climbing",
    meta: { habit: "climbing", light: "sun-partial", color: "#5f8f4a" },
  },
  {
    id: "PLANT-CLIMB-002",
    sku: "PLN-CLB-02",
    category: "plant",
    name: "Climbing Rose",
    status: "active",
    description:
      "The flowering climber shown in the concept imagery. Needs support and regular pruning.",
    price: { amount: 260, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    requires: ["PLANTER-TRELLIS-001"],
    tags: ["climbing", "flowering"],
    assetKey: "plant:climbing",
    meta: { habit: "climbing", light: "sun", color: "#6d9a52", bloom: "#d4577a" },
  },
  {
    id: "PLANT-HANG-001",
    sku: "PLN-HNG-01",
    category: "plant",
    name: "Trailing Pothos",
    status: "active",
    description: "Hardy trailing foliage for hanging planters. Prefers shade.",
    price: { amount: 120, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    requires: ["PLANTER-HANG-001"],
    tags: ["hanging", "shade"],
    assetKey: "plant:hanging",
    meta: { habit: "hanging", light: "shade", color: "#79a45c" },
  },
  {
    id: "PLANT-SHRUB-001",
    sku: "PLN-SHR-01",
    category: "plant",
    name: "Ornamental Grasses",
    status: "active",
    description: "Soft movement at the edge planters. Low maintenance.",
    price: { amount: 95, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    tags: ["planter", "low-maintenance"],
    assetKey: "plant:shrub",
    meta: { habit: "planter", light: "sun", color: "#8fae6a" },
  },
  {
    id: "PLANT-SHRUB-002",
    sku: "PLN-SHR-02",
    category: "plant",
    name: "Mixed Foliage Bed",
    status: "active",
    description: "A layered mix of leaf shapes and tones for the planter boxes.",
    price: { amount: 180, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    tags: ["planter"],
    assetKey: "plant:shrub",
    meta: { habit: "planter", light: "sun-partial", color: "#6b9450" },
  },
  {
    id: "PLANT-AQUA-001",
    sku: "PLN-AQU-01",
    category: "plant",
    name: "Aquatic Planting",
    status: "active",
    description: "Submerged planting for the aquarium. Needs the aquatic tray.",
    price: { amount: 160, currency: "SAR", status: "placeholder" },
    pricingMode: "flat",
    requires: ["AQUARIUM"],
    tags: ["aquatic"],
    assetKey: "plant:aquatic",
    meta: { habit: "aquatic", color: "#3f8f5e" },
  },
  {
    id: "PLANT-TREE-001",
    category: "plant",
    name: "Specimen Tree",
    status: "future",
    description: "A large planted tree integrated with the pavilion.",
    unavailableReason:
      "Root volume, drainage and dead load make this a site-specific landscaping project rather than a configurator option.",
    assetKey: "plant:tree",
  },
];
